version: '3.4'

services:
  roomiesbot:
    image: ${DOCKER_REGISTRY-}roomiesbot
    build:
      context: .
      dockerfile: RoomiesBot/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - Flypack__Username=${FLYPACK_USERNAME}
      - Flypack__Password=${FLYPACK_PASSWORD}
      - Telegram__AccessToken=${TELEGRAM_ACCESS_TOKEN}
      - Telegram__ChannelIdentifier=${TELEGRAM_CHANNEL_IDENTIFIER}